FitJournal/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('articles-list/', views.articles_list, name='articles-list'),
    path('<slug:article_slug>/', views.article, name='article')
]

FitJournal/tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [
    path('calculator_1rm', views.calculator_1rm, name='calculator_1rm')
]

FitJournal/trainings/urls.py
from django.urls import path
from . import views

app_name = 'trainings'

urlpatterns = [
    path('', views.trainings_list, name='trainings_list')
]

FitJournal/users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    # urls для смены пароля
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='users/password_change.html',
                                               success_url=reverse_lazy('users:password_change_done')),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    # urls для просмотра и добавления веса пользователя
    path('add_weight/', views.add_weight, name='add_weight'),
    path('user_weight/', views.weight_journal, name='user_weight'),

    # Настройки пользователя
    path('settings/', views.user_settings, name='profile_settings'),

    # urls для сброса пароля
    path("password_reset/", auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('users:password_reset_done')
    ), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password_reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('users:password_reset_complete')
    ),
         name="password_reset_confirm"),
    path("password_reset/complete", auth_views.PasswordResetCompleteView.as_view(),
         name="password_reset_complete"),
    path('<username>/', views.user_profile, name='profile')
]

FitJournal/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Этот тег отвечает за масштабирование контента в зависимости от девайса  -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS core -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'custom.css' %}" rel="stylesheet">

    <!-- Custom JS -->
    {% block custom_js %} {% endblock %}

    <title>{{title}}{%block title%}{% endblock %}</title>

</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-sm bg-primary" data-bs-theme="dark">
    <div class="container" style="padding-top: 1vh; padding-bottom: 1vh; color: white;">
        <a class="navbar-brand" href="{% url 'index' %}">JournalFitRu</a>
        <div class="my_nal_links">
            <a class="nav-link" href="{% url 'articles:articles-list' %}">Статьи</a>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    Калькуляторы
                </a>
                <ul class="dropdown-menu shadow p-3 mb-5 bg-white">
                    <li><a class="dropdown-item" href="{% url 'tools:calculator_1rm' %}">Одноповторный
                        максимум</a></li>
                </ul>
            </div>
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'trainings:trainings_list' %}">Журнал тренировок</a>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    {{ request.user.username }}
                </a>
                <ul class="dropdown-menu shadow p-3 mb-5 bg-white">
                    <li><a class="dropdown-item" href="{% url 'users:profile' request.user.username %}">Профиль</a></li>
                    {% if request.user.is_superuser %}
                    <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-меню</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'users:profile_settings' %}">Настройки</a></li>
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Выход</a></li>
                </ul>
            </div>
            {% else %}
            <a class="nav-link" href="{% url 'login' %}">Вход</a>
            {% endif %}
        </div>
    </div>
</nav>

<!-- Content -->
<div class="container mt-4" style="overflow: hidden;">
    <!-- Сообщения -->
    {% if messages %}
    <ul class="message-box">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message|safe }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <!-- Блок контента -->
    {% block content %} {% endblock %}
</div>

<!-- Footer -->
<footer class="sticky-footer bg-primary">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'about' %}" class="nav-link px-2">О нас</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2">Политика конфиденциальности</a></li>
    </ul>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

FitJournal/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous%}
        <a href="?page={{ page.previous_page_number }}"> Предыдущая </a>
        {% endif %}
        <span class="current">
            Страница {{ page.number }} из {{ page.paginator.num_pages }}
        </span>
        <span>
            {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}"> Следующая </a>
            {% endif %}
        </span>
    </span>
</div>

FitJournal/templates/test.html
{% extends 'base.html' %}

{% block title %} Test {% endblock %}

{% block content %}
{% if msg %}
<h1>{{ msg }}</h1>
{% endif %}
{% endblock %}