FitJournal/tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [
    path('calculator_1rm', views.calculator_1rm, name='calculator_1rm')
]

FitJournal/users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    # urls для смены пароля
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='users/password_change.html',
                                               success_url=reverse_lazy('users:password_change_done')),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    # urls для просмотра и добавления веса пользователя
    path('add_weight/', views.add_weight, name='add_weight'),
    path('user_weight/', views.weight_journal, name='user_weight'),

    # Настройки пользователя
    path('settings/', views.user_settings, name='profile_settings'),

    # urls для сброса пароля
    path("password_reset/", auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('users:password_reset_done')
    ), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password_reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('users:password_reset_complete')
    ),
         name="password_reset_confirm"),
    path("password_reset/complete", auth_views.PasswordResetCompleteView.as_view(),
         name="password_reset_complete"),
    path('<username>/', views.user_profile, name='profile')
]

FitJournal/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils import timezone
from trainings.models import Activity


class UserProfile(models.Model):
    """
    Модель профиля пользователя связанная со стандартной для пользователя
    """

    class Gender(models.TextChoices):
        no_data = ("-", "Выберите")
        male = ("М", "Муж.")
        female = ("Ж", "Жен.")

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    height = models.IntegerField(blank=True, null=True)
    gender = models.CharField(max_length=1,
                              choices=Gender.choices,
                              default=Gender.no_data)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()


class UserWeight(models.Model):
    """
    Модель описывающая вес пользователя в определенный промежуток времени
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=False)
    weight_date = models.DateField(default=timezone.now, unique=True)
    weight = models.FloatField()

    class Meta:
        """
        Индексы для модели
        """
        indexes = [
            models.Index(fields=['user', '-weight_date'])
        ]


class UserTraining(models.Model):
    """
    Модель хранящая тренировку пользователя
    """
    # Пользователь
    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=False)
    # Дата время тренировки
    training_date = models.DateTimeField(default=timezone.now, unique=True)
    # Тип тренировки
    training_type = models.ForeignKey(Activity, on_delete=models.SET_NULL, null=True, blank=True)
    # Данные о тренировке в формате JSON
    exercise_data = models.JSONField(default=dict)

    def __str__(self):
        """
        Дружелюбная реализация строкового представления
        """
        res = str(self.user) + " " + str(self.training_type) + " " + str(self.training_date)
        return res

FitJournal/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import UserProfile, UserWeight
from django import forms


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={
        'class': "form-control mt-2",
        'placeholder': "Введите имя пользователя"
    }))
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={
        'class': "form-control mt-2",
        'placeholder': "Введите пароль"
    }))

    class Meta:
        model = User
        fields = ('username', 'password')

    def clean(self):
        """
        Кастомный метода валидации для поля
        """
        user = self.cleaned_data['username']
        if not User.objects.filter(username=user).exists():
            msg = ValidationError("Такого пользователя не существует")
            self.add_error("username", msg)
        user_pass = self.cleaned_data['password']
        if not User.objects.filter(username="SlavaTatanov")[0].check_password(user_pass):
            self.add_error("password", ValidationError("Неверный пароль"))
        return self.cleaned_data


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={
        'class': "form-control mt-2",
        'placeholder': "Имя пользователя"
    }))
    email = forms.CharField(label="e-mail", widget=forms.EmailInput(attrs={
        'class': "form-control mt-2",
        'placeholder': "Введите адрес эл. почты"
    }))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={
        'class': "form-control mt-2",
        'placeholder': "Введите пароль"
    }))
    password2 = forms.CharField(label="Повторите пароль", widget=forms.PasswordInput(attrs={
        'class': "form-control mt-2",
        'placeholder': "Подтвердите пароль"
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileForm(forms.ModelForm):
    height = forms.IntegerField(label="Рост")
    gender = forms.ChoiceField(label="Пол",
                               choices=UserProfile.Gender.choices)

    class Meta:
        model = UserProfile
        fields = ('height', 'gender')


class UserWeightForm(forms.ModelForm):
    weight_date = forms.DateField(label="Дата", widget=forms.DateInput(attrs={'type': 'date'}))
    weight = forms.FloatField(label="Вес")

    class Meta:
        model = UserWeight
        fields = ('weight_date', 'weight')

FitJournal/users/views.py
from datetime import timedelta, time
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from django.contrib import auth, messages
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import UserProfile, UserWeight
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm, UserWeightForm


def login(request: HttpRequest):
    context = {'form': UserLoginForm()}
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)  # Создаем форму и передаем в нее дату, для дальнейшей обработки
        if form.is_valid():  # Проверяем валидность
            username = request.POST['username']
            password = request.POST['password']  # Берем значения из формы
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)  # Если такой юзер есть, то авторизуем
                next_page = request.POST['next']  # Если был параметр next перенаправляем туда
                if next_page:
                    return HttpResponseRedirect(next_page)
                return HttpResponseRedirect(reverse('index'))
        else:
            context = {'form': form}
    return render(request, 'users/login.html', context=context)


def register(request: HttpRequest):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            # Если данные валидные то сохранить юзера
            form.save()
            return HttpResponseRedirect(reverse('login'))
        else:
            # Если не прошла валидация вернем форму с ошибками
            context = {'form': form}
    # Если метод GET передать форму
    else:
        context = {'form': UserRegistrationForm()}
    return render(request, 'users/register.html', context=context)


def user_profile(req: HttpRequest, username):
    user_in_db = User.objects.filter(username=username)
    if user_in_db:
        if req.user.is_authenticated:
            current_user = req.user.get_username()
        else:
            current_user = None
        context = {'user': username}
        if current_user and current_user == username:
            return render(req, 'users/user_profile.html', context)
        else:
            return render(req, 'users/public_user_profile.html', context)
    else:
        return render(req, 'users/not_user.html')


def logout(req: HttpRequest):
    """
    Представление для выхода из профиля пользователя
    """
    auth.logout(req)
    return HttpResponseRedirect(reverse('index'))


@login_required
def user_settings(req: HttpRequest):
    """
    Представление для настроек профиля пользователя
    """
    if req.method == "POST":
        if req.user.is_authenticated:
            instance_profile = UserProfile.objects.get(user=req.user)
            form = UserProfileForm(data=req.POST, instance=instance_profile)
            if form.is_valid():
                form.save()
                response = redirect("users:profile_settings")
                messages.success(req, "Профиль успешно сохранен!")
                return response
    elif req.method == "GET":
        # Если метод запроса GET, то мы делаем запрос к базе данных и заполняем форму.
        # Если данных нет, то вернем пустую форму, если есть - заполненную.
        try:
            profile = UserProfile.objects.get(user=req.user)
        except UserProfile.DoesNotExist:
            profile = None
        form = UserProfileForm(instance=profile)
        user = req.user.get_username()

        # Получаем данные по весу пользователя
        try:
            user_weight_profile = UserWeight.objects.filter(user=req.user).order_by("-weight_date")[0]
            user_weight = user_weight_profile.weight
        except UserWeight.DoesNotExist:
            user_weight = "Нет данных"

        # Собираем контекст и отправляем страницу
        context = {'user': user, 'profile_form': form, 'user_weight': user_weight}
        return render(req, 'users/user_settings.html', context=context)


@login_required
def test_view(req: HttpRequest):
    return render(req, 'test.html', {'msg': 'Это тестовое сообщение'})


@login_required
def weight_journal(req: HttpRequest):
    """
    Запрашиваем для пользователя данные по его весу, делаем два списка, все запросы и за последние полгода.
    """
    # Получаем текущую дату
    current_date = timezone.now().date()
    # Получаем дату полгода назад
    six_month = current_date - timedelta(days=180)

    # Делаем запрос данных по весу для пользователя
    user_name = req.user
    weight_data = UserWeight.objects.filter(user=user_name).order_by('-weight_date')

    # Создаем объект Paginator из данных по весу
    paginator = Paginator(weight_data, 5)

    # Получаем страницу
    page_number = req.GET.get('page', 1)

    # Получаем набор данных для страницы
    try:
        weight_data_page = paginator.page(page_number)
    except PageNotAnInteger or EmptyPage:
        weight_data_page = paginator.page(1)

    # Создаем отдельный список для последних 6 месяцев
    last_six_month_label = []
    last_six_month_data = []
    all_label = []
    all_data = []
    for item in weight_data:
        if item.weight_date > six_month:
            last_six_month_data.insert(0, item.weight)
            last_six_month_label.insert(0, item.weight_date.isoformat())
        else:
            all_data.insert(0, item.weight)
            all_label.insert(0, item.weight_date.isoformat())

    # Проверяем есть ли указание о типе графика с данными
    data_type = req.GET.get('data_type')

    # Собираем контекст
    context = {"all_data": all_data + last_six_month_data,
               "all_label": all_label + last_six_month_label,
               "last_six_month_data": last_six_month_data,
               "last_six_month_label": last_six_month_label,
               "data_type": data_type,
               "weight_data_page": weight_data_page}
    return render(req, 'users/weight_journal.html', context=context)


@login_required
def add_weight(req: HttpRequest):
    if req.method == "POST":
        form = UserWeightForm(data=req.POST)
        if form.is_valid():
            # Сохраняем форму, прицепляем к ней экземпляр пользователя и сохраняем в базу данных.
            form.save(commit=False)
            form.instance.user = req.user
            form.save()
            messages.success(req, "Вес успешно добавлен")
    else:
        form = UserWeightForm()
    return render(req, 'users/add_weight.html', {'form': form})

FitJournal/users/templates/users/add_weight.html
{% extends "base.html" %}

{% block title %}Ввод веса{% endblock %}

{% block content %}
<h2>Добавить измерения веса</h2>
<hr>
<form method="post">
    {% csrf_token %}
    <div style="margin-bottom: 1vh;">
        {{ form.weight_date.errors }}
        <label for="{{form.weight_date.id_for_label}}">Дата</label>
        {{ form.weight_date }}
    </div>
    <div>
        {{ form.weight.errors }}
        <label for="{{form.weight.id_for_label}}">Вес</label>
        {{ form.weight }}
    </div>
    <button type="submit" class="btn btn-primary my-4">Сохранить</button>

    <!-- Возврат к журналу веса -->
    <a href="{% url 'users:user_weight' %}" class="btn btn-primary my-4">Журнал веса</a>

</form>
{% endblock %}

FitJournal/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="card shadow-lg border-0 rounded-lg bg-primary bg-gradient mobile-width-90 mobile-mt-0" style="width:50%; margin-top: 3rem;">
        <div class="card-header">
            <h3 class="text-center font-weight-light my-5">Авторизация</h3>
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group my-4">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
                <div> {{ field.errors }} </div>
                {% endfor %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <div style="display: flex; justify-content: center; align-items: center;">
                  <button type="submit" class="btn btn-primary my-4" style="background:#fff; color:black">Авторизация</button>
                </div>
                <p style="display: flex; justify-content: center; align-items: center; line-height: 1; color: white;">Нет аккаунта?
                      <a href="{% url 'register' %}" style="color: silver; margin: 10px" >Зарегистрироваться!</a>
                  </p>
                <a href="{% url 'users:password_reset' %}" style="display: flex; justify-content: center; align-items: center; line-height: 1; color: silver; margin-bottom: 2vh;">Забыли пароль?</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

FitJournal/users/templates/users/not_user.html
{% extends "base.html" %}

{% block content %}
    <h1 style="text-align: center;">Пользователь не найден</h1>
{% endblock %}

FitJournal/users/templates/users/password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
<h1>Смена пароля</h1>
<p>Для смены пароля заполните форму ниже</p>
<hr>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary my-4">Сменить</button>
</form>
{% endblock %}

FitJournal/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}Пароль успешно изменен{% endblock %}

{% block content %}
<h1>Пароль успешно изменен</h1>
<p>Вернутся на <a href="{% url 'index' %}">главную страницу.</a></p>
{% endblock %}

FitJournal/users/templates/users/public_user_profile.html
{% extends "base.html" %}

{% block content %}
    <h1>Профиль пользователя {{ user }}</h1>
{% endblock %}

FitJournal/users/templates/users/register.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="card shadow-lg border-0 rounded-lg mt-5 mb-5 bg-primary bg-gradient" style="width:50%">
        <div class="card-header">
            <h3 class="text-center font-weight-light my-5">Регистрация</h3>
            <form action="{% url 'register' %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group my-4">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary my-4" style="background:#fff; color:black">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

FitJournal/users/templates/users/user_profile.html
{% extends "base.html" %}

{% block content %}
    <h1>Профиль для: {{ user }}</h1>
{% endblock %}

FitJournal/users/templates/users/user_settings.html
{% extends "base.html" %}

{% block content %}
<h1>Настройки {{ user }}</h1>
<hr/>
<div style="display: flex;">
    <div style="padding-right: 5vw;">
        <p>Пароль:</p>
    </div>
    <div>
        <a href="{% url 'users:password_change' %}">Сменить</a>
    </div>
</div>
<h2>Физические данные</h2>
<hr/>
<div>
    <form action="#" method="post">
        {% csrf_token %}
        <div style="display: flex;">
            <div style="padding-right: 5vw;">
                {% for field in profile_form %}
                <p>{{ field.label }}:</p>
                {% endfor %}
            </div>
            <div>
                {% for field in profile_form %}
                <p>{{ field }}</p>
                {% endfor %}
            </div>
        </div>

        <!-- Элементы не относящиеся к форме -->
        <div style="display: flex;">
           <p style="padding-right: 1.9vw;">Текущий вес:</p>
           <p> {{user_weight}} кг. <a href="{% url 'users:user_weight' %}">Журнал веса</a> </p>
        </div>
        <button type="submit" class="btn btn-primary my-4">Сохранить</button>
    </form>
</div>
{% endblock %}

FitJournal/users/templates/users/weight_journal.html
{% extends "base.html" %}
{% load static %}

{% block custom_js %}
<!-- Загружаем Chart.js адаптер времени и свой js с графиком -->
<script src="{% static 'js/chart.min.js' %}"></script>
<script src="{% static 'js/chartjs-adapter-date-fns.bundle.min.js' %}"></script>
<script src="{% static 'js/weight_chart_script.js' %}"></script>
{% endblock %}

{% block title %}Журнал веса{% endblock %}

{% block content %}
<h1>График веса</h1>
<hr>
<!-- Основной div с графиками и данными -->
<div style="display:flex">
<div style="width: 60%; margin-right: 5%;">
<!-- div с графиками -->
<div>
    <!-- Наш график -->
    <div style="margin-bottom: 0,8em!important;">
        <canvas id="weight_chart"></canvas>
    </div>
</div>


<!-- Скрипт создания графика -->
<script>
    {% if data_type == "all" %}
    chart = createChart({{ all_label | safe }}, {{ all_data}})
    {% else %}
    chart = createChart ({{ last_six_month_label | safe }}, {{ last_six_month_data}})
    {% endif %}
</script>

<!-- Переключатель графика 6 месяцев - все время -->
<div class="mt-4">
    <div class="form-check">
    {% if data_type == "all" %}
    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
    {% else %}
    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1"  checked>
    {% endif %}
  <label class="form-check-label" for="flexRadioDefault1">
    6 месяцев
  </label>
</div>
<div class="form-check">
  {% if data_type == "all" %}
  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
  {% else %}
  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
  {% endif %}
  <label class="form-check-label" for="flexRadioDefault2">Все время</label>
</div>
</div>

<script>
    // Получаем ссылки на элементы radio
    const radio1 = document.getElementById('flexRadioDefault1');
    const radio2 = document.getElementById('flexRadioDefault2');

    // Добавляем обработчик события change
    radio1.addEventListener('change', function() {
        // Вызываем функцию createChart с соответствующими параметрами
        chart.destroy()
        chart = createChart({{ last_six_month_label | safe }}, {{ last_six_month_data }});
        localStorage.setItem('data_type_weight', 'six');
    });

    radio2.addEventListener('change', function() {
        // Вызываем функцию createChart с соответствующими параметрами
        chart.destroy()
        chart = createChart({{ all_label | safe }}, {{ all_data}});
        localStorage.setItem('data_type_weight', 'all');
    });
</script>

<!-- Кнопка добавить вес -->
<div class="mt-4">
  <a href="{% url 'users:add_weight' %}" class="btn btn-primary">Добавить данные</a>
</div>

</div>

<!-- Список записей -->
    <div style="display: flex; flex-direction: column; width: 100%">
    <div class="mb-5">
        <h2>Записи:</h2>
        <hr>
        <table class="table table-striped table-bordered " style="width: 100%;">
            <thead>
            <tr>
                <th scope="col">Дата</th>
                <th scope="col">Вес</th>
                <th scope="col"></th>
            </tr>
            </thead>
        <tbody>
        {% for data in weight_data_page %}
        <tr>
        <td><p>{{ data.weight_date }}</p></td>
        <td><p>{{ data.weight }}</p></td>
        <td><a href="#">Удалить</a></td>
        </tr>
        {% endfor %}
        </tbody>

        </table>
    </div>
    <div style="flex-grow: 1;">
    {% include 'pagination.html' with page=weight_data_page %}
    </div>
    </div>

</div>


{% endblock %}